import math

ak = 6378245
eksk = 0.0066934223
PI = math.pi
ck = 6399699

class Ellipsoid:
    def   Reducir():
      ya=-120943.742187500
      xa=5723499.000000000
      Aac=110.5*PI/180
      Sac=45924.432
      sphugA=62.213*PI/180
      sphugB=50.339*PI/180
      sphugC=67.450*PI/180
      B=51.628*PI/180
      L=(25.25373*PI)/180
      L0=27*PI/180
      lmal=L-L0
      nmal=eksk*math.cos(B)
      Bx=0.902037084
      Nx=6391426.000
      nmalx=eksk*math.cos(Bx)
      Bm=55*PI/180
      cos2Bx=math.cos(Bx)*math.cos(Bx)
      cos4Bx=cos2Bx*cos2Bx
      z=ya/(Nx*math.cos(Bx))
      z2=z*z
      cos2B=math.cos(B)*math.cos(B)
      l2=lmal*lmal
      sblizAp=(1-((0.33333-0.00225*cos4Bx)-(0.2-0.067*cos2Bx)*z2)*z2)*z*math.sin(Bx)
      sblizAg=(1+((0.33333+0.006674*cos2B)+(0.2*cos2B-0.0067)*l2)*l2*cos2B)*lmal*math.sin(B)
      xb=5660500
      yb=-125000
      xc=5692000
      yc=-93000
      f  =0.00253
      Rm=ak*(1-0.5*eksk*eksk*math.cos(2*Bm))
      ymac=(yc+ya)/2000
      ymab=(ya+yb)/2000
      ymbc=(yb+yc)/2000
      Sab=Sac*math.sin(sphugC)/math.sin(sphugB)
      Sbc=Sac*math.sin(sphugA)/math.sin(sphugB)
      popravAC=-1*f*ymac*(xc/1000-xa/1000)
      popravAB=-1*f*ymab*(xb/1000-xa/1000)
      popravCB=-1*f*ymbc*(xb/1000-xc/1000)
      delSac=0.123*(ymac/100)*(ymac/100)*Sac
      delSab=0.123*(ymab/100)*(ymab/100)*Sab
      delSbc=0.123*(ymbc/100)*(ymbc/100)*Sbc
      alfaAC=Aac*180/PI-sblizAp*180/PI+popravAC/3600
      popravA=popravAC-popravAB
      popravB=-1*popravAB-(-1*popravCB)
      popravC=popravCB-(-1*popravAC)
      alfaAC180=alfaAC*PI/180+PI
      alfaACab=alfaAC*PI/180-sphugA+popravA/3600
      alfaACbc=alfaAC180+sphugC+popravC/3600
      skonb=Sac+delSac/1000
      skonc=Sab+delSab/1000
      skona=Sbc+delSbc/1000
      cosalfaACac=math.cos(alfaAC)
      cosalfaACab=math.cos(alfaACab)
      cosalfaACbc=math.cos(alfaACbc)
      sinalfaACac=math.sin(alfaAC)
      sinalfaACab=math.sin(alfaACab)
      sinalfaACbc=math.sin(alfaACbc)
      xac=xa/1000+xc/1000-xa/1000
      xab=xa/1000+xb/1000-xa/1000
      xcb=xc/1000+xb/1000-xc/1000
      yac=ya/1000+yc/1000-ya/1000
      yab=ya/1000+yb/1000-ya/1000
      ycb=yc/1000+yb/1000-yc/1000
      plosA=sphugA+popravA/206265
      plosB=sphugB+popravB/206265
      plosC=sphugC+popravC/206265
      sumpop=popravA+popravB+popravC
      sumugsp=sphugA+sphugB+sphugC
      sumugpl=plosA+plosB+plosC
      e=f*Sbc*Sac*math.sin(plosC)/1000000
      
      #print("ЗНАЧЕНИЕ ПАРАМЕТРА POPRAVAC v sekundah = %.0f  "  %(popravAC)
      #print("ЗНАЧЕНИЕ ПАРАМЕТРА POPRAVAB v sekundah = %.0f  "  %(popravAB)
      #print("ЗНАЧЕНИЕ ПАРАМЕТРА POPRAVBC v sekundah = %.0f  "  %(popravCB)
      #print("ЗНАЧЕНИЕ ПАРАМЕТРА -POPRAVAC v sekundah = %.0f  "  %(-1*popravAC)
      #print("ЗНАЧЕНИЕ ПАРАМЕТРА -POPRAVAB v sekundah = %.0f  "  %(-1*popravAB)
      #print("ЗНАЧЕНИЕ ПАРАМЕТРА -POPRAVBC v sekundah = %.0f  "  %(-1*popravCB)
      #print("ЗНАЧЕНИЕ ПАРАМЕТРА sblizAp = %.9f  "  %(sblizAp)
      #print("ЗНАЧЕНИЕ ПАРАМЕТРА sblizAg = %.9f  "  %(sblizAg)
      #print("ЗНАЧЕНИЕ ПАРАМЕТРА Sab = %.9f  "  %(Sab)
      #print("ЗНАЧЕНИЕ ПАРАМЕТРА Sbc = %.9f  "  %(Sbc)
      #print("ЗНАЧЕНИЕ ПАРАМЕТРА delSac = %.0f  "  %(delSac/1000)
      #print("ЗНАЧЕНИЕ ПАРАМЕТРА delSab = %.0f  "  %(delSab/1000)
      #print("ЗНАЧЕНИЕ ПАРАМЕТРА delSbc = %.0f  "  %(delSbc/1000)
      #print("ЗНАЧЕНИЕ ПАРАМЕТРА alf  aAC = %.6f  "  %(alf  aAC)
      #print("ЗНАЧЕНИЕ ПАРАМЕТРА POPRAVA = %.0f  "  %(popravA)
      #print("ЗНАЧЕНИЕ ПАРАМЕТРА POPRAVB = %.0f  "  %(popravB)
      #print("ЗНАЧЕНИЕ ПАРАМЕТРА POPRAVC = %.0f  "  %(popravC)
      #print("znachenie parametra xac = %.3f  "  %(xac)
      #print("znachenie parametra xab = %.3f  "  %(xab)
      #print("znachenie parametra xcb = %.3f  "  %(xcb)
      #print("znachenie parametra yac = %.3f  "  %(yac)
      #print("znachenie parametra yab = %.3f  "  %(yab)
      #print("znachenie parametra ycb = %.3f  "  %(ycb)
      
      print("----------таблица 7--------")
      print("ЗНАЧЕНИЕ ПАРАМЕТРА alf  aAC  = %.9f "  %(alfaAC*PI/180))
      print("значение параметра alf  aAC+180 = %.9f  "  %(alfaAC180))
      print("значение сферического угла А = %.9f  "  %(sphugA))
      print("значение сферического угла С = %.9f  "  %(sphugC))
      print("значение поправки в угол А = %.9f  "  %(popravA))
      print("значение поправки в угол B = %.9f  "  %(popravB))
      print("значение поправки в угол С = %.9f  "  %(popravC))
      print("значение дирекционного угла АС = %.9f  "  %(alfaAC*PI/180))
      print("значение дирекционного угла АВ = %.9f  "  %(alfaACab))
      print("значение дирекционного угла ВС = %.9f  "  %(alfaACbc))
      print("значение длины стороны b = %.9f  "  %(Sac))
      print("значение длины стороны c = %.9f  "  %(Sab))
      print("значение длины стороны a = %.9f  "  %(Sbc))
      print("значение дельты s при b = %.9f  "  %(delSac/1000))
      print("значение дельты s при c = %.9f  "  %(delSbc/1000))
      print("значение дельты s при а = %.9f  "  %(delSab/1000))
      print("значение стороны b = %.9f  "  %(skonb))
      print("значение стороны c = %.9f  "  %(skonc))
      print("значение стороны a = %.9f  "  %(skona))
      print("значение координаты xa = %.9f  "  %(xa/1000))
      print("значение координаты xc = %.9f  "  %(xc/1000))
      print("значение разности координат xc-xa = %.9f  "  %(xc/1000-xa/1000))
      print("значение разности координат xb-xa = %.9f  "  %(xb/1000-xa/1000))
      print("значение разности координат xb-xc = %.9f  "  %(xb/1000-xc/1000))
      print("значение координаты xc = %.9f  "  %(xc/1000))
      print("значение координаты xb = %.9f  "  %(xb/1000))
      print("значение координаты ya = %.9f  "  %(ya/1000))
      print("значение координаты yb = %.9f  "  %(yb/1000))
      print("значение разности координат yc-ya = %.9f  "  %(yc/1000-ya/1000))
      print("значение разности координат yb-ya = %.9f  "  %(yb/1000-ya/1000))
      print("значение разности координат yb-yc = %.9f  "  %(yb/1000-yc/1000))
      print("значение координаты yc = %.9f  "  %(yc/1000))
      print("значение координаты yb = %.9f  "  %(yb/1000))
      print("значение широты треугольника Bm = %.9f  "  %(Bm*180/PI))
      print("значение ym для АС = %.9f  "  %(ymac))
      print("значение уm для АВ = %.9f  "  %(ymab))
      print("значение ym для ВС = %.9f  "  %(ymbc))
      print("значение yc-ya/6 = %.9f  "  %((yc/1000-ya/1000)/6))
      print("значение yb-ya/6 = %.9f  "  %((yb/1000-ya/1000)/6))
      print("значение yb-yc/6 = %.9f  "  %((yb/1000-yc/1000)/6))
      print("значение параметра Rm = %.9f  "  %(Rm))
      print("значение параметра ymac^3/3Rm^2 = %.9f  "  %((ymac*ymac*ymac)/(3*Rm*Rm)))
      print("значение параметра ymab^3/3Rm^2 = %.9f  "  %((ymab*ymab*ymab)/(3*Rm*Rm)))
      print("значение параметра ymbc^3/3Rm^2 = %.9f  "  %((ymbc*ymbc*ymbc)/(3*Rm*Rm)))
      print("значение параметра f  m = %.9f  "  %(f))
      print("значение поправки АС = %.9f  "  %(popravAC))
      print("значение поправки АВ = %.9f  "  %(popravAB))
      print("значение поправки ВС = %.9f  "  %(popravCB))
      print("значение поправки СА = %.9f  "  %(-1*popravAC))
      print("значение поправки ВА = %.9f  "  %(-1*popravAB))
      print("значение поправки СВ = %.9f  "  %(-1*popravCB))
      print("значение параметра ymac^2/2Rm^2 = %.9f  "  %((ymac*ymac)/(2*Rm*Rm)))
      print("значение параметра ymab^2/2Rm^2 = %.9f  "  %((ymab*ymab)/(2*Rm*Rm)))
      print("значение параметра ymbc^2/2Rm^2 = %.9f  "  %((ymbc*ymbc)/(2*Rm*Rm)))
      print("значение параметра (yc-ya)^2/24Rm^2 = %.9f  "  %(((yc-ya)*(yc-ya))/(24*Rm*Rm)))
      print("значение параметра (yb-ya)^2/24Rm^2 = %.9f  "  %(((yb-ya)*(yb-ya))/(24*Rm*Rm)))
      print("значение параметра (yb-yc)^2/24Rm^2 = %.9f  "  %(((yb-yc)*(yb-yc))/(24*Rm*Rm)))
      print("значение параметра ymac^4/24Rm^4 = %.9f  "  %((ymac*ymac*ymac*ymac)/(24*Rm*Rm*Rm*Rm)))
      print("значение параметра ymab^4/24Rm^4 = %.9f  "  %((ymab*ymab*ymab*ymab)/(24*Rm*Rm*Rm*Rm)))
      print("значение параметра ymbc^4/24Rm^4 = %.9f  "  %((ymbc*ymbc*ymbc*ymbc)/(24*Rm*Rm*Rm*Rm)))
      print("значение параметра delSac = %.9f  "  %(delSac/1000))
      print("значение параметра delSab = %.9f  "  %(delSab/1000))
      print("значение параметра delSbc = %.9f  "  %(delSbc/1000))
      print("значение параметра dAC = %.9f  "  %(Sac+delSac/1000))
      print("значение параметра dAB = %.9f  "  %(Sab+delSab/1000))
      print("значение параметра dBC = %.9f  "  %(Sbc+delSbc/1000))
      print("---------Окончательное решение треугольника---------")
      print("сферический угол А = %.9f  "  %(sphugA))
      print("сферический угол В = %.9f  "  %(sphugB))
      print("сферический угол С = %.9f  "  %(sphugC))
      print("поправка в угол А = %.9f  "  %(popravA))
      print("поправка в угол В = %.9f  "  %(popravB))
      print("поправка в угол С = %.9f  "  %(popravC))
      print("плоский угол А = %.9f  "  %(plosA))
      print("плоский угол В = %.9f  "  %(plosB))
      print("плоский угол С = %.9f  "  %(plosC))
      print("синус плоского угла А = %.9f  "  %(math.sin(plosA)))
      print("синус плоского угла В = %.9f  "  %(math.sin(plosB)))
      print("синус плоского угла С = %.9f  "  %(math.sin(plosC)))
      print("сумма сферических углов = %.9f  "  %(sumugsp))
      print("сумма плоских углов = %.9f  "  %(sumugpl))
      print("сумма поправок = %.9f  "  %(sumpop))
      print("значение dBC = %.9f  "  %(Sbc+delSbc/1000))
      print("значение dAC = %.9f  "  %(Sac+delSac/1000))
      print("значение dAB = %.9f  "  %(Sab+delSab/1000))
      print("значение контроля = %.9f  "  %(e))
      print("----------точное значение дирекционного угла АС---------- = %.9f  "  %((Aac-sblizAp+popravAC/206265)*180/PI))
      print("----------вычисление окончательных значений координат вершин треугольника----------")
      print("дирекционный угол АС = %.9f  "  %(alfaAC))
      print("дирекционный угол АС+180 = %.9f  "  %(alfaAC180*180/PI))
      print("плоский угол А = %.9f  "  %(plosA*180/PI))
      print("плоский угол С = %.9f  "  %(plosC*180/PI))
      print("дирекционный угол АВ = %.9f  "  %(alfaACab*180/PI))
      print("дирекционный угол ВС = %.9f  "  %(alfaACbc*180/PI))
      print("косинус дирекционного угла АС = %.9f  "  %(math.cos(alfaAC*PI/180)))
      print("косинус дирекционного угла АВ = %.9f  "  %(math.cos(alfaACab)))
      print("косинус дирекционного угла ВС = %.9f  "  %(math.cos(alfaACbc)))
      print("сторона d AC = %.9f  "  %(Sac+delSac/1000))
      print("сторона d AB = %.9f  "  %(Sab+delSab/1000))
      print("сторона d BC = %.9f  "  %(Sbc+delSbc/1000))
      print("синус угла АС = %.9f  "  %(math.sin(alfaAC*PI/180)))
      print("синус угла АВ = %.9f  "  %(math.sin(alfaACab)))
      print("синус угла ВС = %.9f  "  %(math.sin(alfaACbc)))
      print("координата xa = %.9f  "  %(xa))
      print("координата xc = %.9f  "  %(xc))
      print("дельта координаты xa = %.9f  "  %(xc-xa))
      print("дельта координаты xb = %.9f  "  %(xb-xa))
      print("дельта координаты xc = %.9f  "  %(xb-xc))
      print("координата xc = %.9f  "  %(xc))
      print("координата xb = %.9f  "  %(xb))
      print("координата ya = %.9f  "  %(ya))
      print("координата yc = %.9f  "  %(yc))
      print("дельта координаты ya = %.9f  "  %(yc-ya))
      print("дельта координаты yb = %.9f  "  %(yb-ya))
      print("дельта координаты yc = %.9f  "  %(yb-yc))
      print("координата yc = %.9f  "  %(yc))
      print("координата yb = %.9f  "  %(yb))
Ellipsoid.Reducir()